name: wappauthenticator
description: A WhatsApp OTP login + registration Flutter app
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-SemiBoldItalic.ttf
        - asset: assets/images/bg.jpg

